try {
    let result = someUndefinedFunction();
  } catch (error) {
    console.log("An error occurred:", error.message);
  }
  
